### ISSUE TITLE
Clean species list

### ISSUE THREAD

**Issue by GeraldineDerroire** [Bioforest-project/species#1]
- [x] https://github.com/Bioforest-project/DataAgr_Species/issues/4
- [x] correct typos 
- [x] correct synonyms
- [x] deal with uncertain misspelling and synonymy (I think manual choices need to be done)

**Comment by sylvainschmitt** [comment]
@Bioforest-project/data-preparation , I finished a first version of species list cleaning based on World Flora Online, see the results here: https://bioforest-project.github.io/species/12_cleaned.html . However, this requires some arbitrary decisions that a computer can't do by itself. For instance:

- 4 species have no matches when limiting misspelling to a distance of 4
- 6 correctly spelled species have several currently accepted names
- 4 misspelled species corresponds to several currently accepted names

This could be the object of a discussion with the team or a subgroup on how to deal with this cases. For instance, should we ask a botanist at some point?

Anyhow, I'll proceed to phylogeny and functional traits by dropping in a first time species without matches and selecting randomly a single currently accepted name per species.

**Comment by GeraldineDerroire** [comment]
great ! 
Yes, we should ask the PI and/or a botanist specialist of the area. But they are not so many "problems"!
