### ISSUE TITLE
Get functionnal traits

### ISSUE THREAD

**Issue by GeraldineDerroire** [Bioforest-project/species#2]

**Comment by sylvainschmitt** [comment]
@Bioforest-project/data-preparation , I finished a first version of species data gathering (names cleaning, phylogeny, and functional traits). I suggest we make a meeting to discuss the process before I go further.

**Comment by mithilaunkule** [comment]
> @Bioforest-project/data-preparation , I finished a first version of species data gathering (names cleaning, phylogeny, and functional traits). I suggest we make a meeting to discuss the process before I go further.

Hi missed this message. Could you schedule a meeting Sylvain? :)

**Comment by sylvainschmitt** [comment]
> > @Bioforest-project/data-preparation , I finished a first version of species data gathering (names cleaning, phylogeny, and functional traits). I suggest we make a meeting to discuss the process before I go further.
> 
> Hi missed this message. Could you schedule a meeting Sylvain? :)

Hi Mithila, unfortunately November will be a complicated period for me to schedule a meeting. However, I was waiting for reacts from the group first, a minima @GeraldineDerroire and @cpiponiot . So maybe in the meantime, you can already have a look to the whole analysis and list your question for a meeting to be defined.

**Comment by cpiponiot** [comment]
@sylvainschmitt I'm back to work and will have a look at your script. Do you still want to meet? I'm available until Nov 12, and after Nov 25.

**Comment by sylvainschmitt** [comment]
The best would be to meet, unfortunately I have little availability between the 11th and the 29th. Could be today or after the 25th.

**Comment by mithilaunkule** [comment]
> The best would be to meet, unfortunately I have little availability between the 11th and the 29th. Could be today or after the 25th.

I'm available anytime today if you want :)

**Comment by sylvainschmitt** [comment]
To be discussed:

- Inclusion of less clean taxa (but already partly discussed / decided)
- The choice of what to do with uncertain taxo information (unidentified, sub-species and undescribed, for the moment everything has been deleted)
- Whether and how to track corrections
- The choice of accepted name in case of doubt
- The choice of TRY traits according to the percentage of coverage and the level of access to the data
- Whether or not to include TALLO
- The imputation method

**Comment by GeraldineDerroire** [comment]
> To be discussed:
> 
> * Inclusion of less clean taxa (but already partly discussed / decided)
> * The choice of what to do with uncertain taxo information (unidentified, sub-species and undescribed, for the moment everything has been deleted)
> * Whether and how to track corrections
> * The choice of accepted name in case of doubt
> * The choice of TRY traits according to the percentage of coverage and the level of access to the data
> * Whether or not to include TALLO
> * The imputation method

On my side, I would add:
* what do we decide for the redundant bit of code from Mithila and I
*  what coordinates do we want to use for checking for the abscence of diplicates in the coordinates
* what do we have to determine if a tree in out of the plot? coordinate of the plot corner? plot dimensions?...

**Comment by sylvainschmitt** [comment]
> The choice of what to do with uncertain taxo information (unidentified, sub-species and undescribed, for the moment everything has been deleted)

To see later.

> Whether and how to track corrections

Track the corrections.

>  The choice of accepted name in case of doubt.

Maybe discuss with a botanist. But not that important and only a few.

>  The choice of TRY traits according to the percentage of coverage and the level of access to the data

Looking at the genus level too. Looking at coverage per site. First smaller group. Consolidated question. Big group.

>  Whether or not to include TALLO.

Maybe kept it only for hmax. Coverage?

>  The imputation method.

Maybe leave it out? Maybe something to be done one the analyses level. Need to be kept for data aggregation if data not shared.

**Comment by sylvainschmitt** [comment]
Géraldine questions for https://github.com/Bioforest-project/inventories/issues/6.

> what do we decide for the redundant bit of code from Mithila and I

Keep Géraldine's code.

> what coordinates do we want to use for checking for the absence of duplicates in the coordinates

Privilege relative to the plot, check is relative to the subplot exists. Different types: Lat/Lon, UTM, Plot level, SubPlot level. Keep the finest level? Check the range of coordinates to be sure. Not all sites have tree coordinates. E.g. Embrapa only subplot attribution as coordinates.

Conclusion check coords exists (!=no column), and then use the finest scale info.

>  what do we have to determine if a tree in out of the plot? coordinate of the plot corner? plot dimensions?...

How to know what is max x and y? Look at data and outliers? If they're outside we want to remove them. But don't we want to get in all this trouble for these few trees? Maybe first map assess and see. Let's see how big a problem it is.

Conclusion: for now we see how much a problem it is. But too see we need to define a rule. Using a quantile +modulo 5 because it will be round?
