### ISSUE TITLE
Share raw species list

### ISSUE THREAD

**Issue by sylvainschmitt** [Bioforest-project/species#4]
@mithilaunkule , from the raw data could you extract a raw species list that I could use for code dev similarly to https://github.com/Bioforest-project/DataAgr_inventories/issues/4 ?

**Comment by mithilaunkule** [comment]
- [ ] one file per site to send to team
- [ ] small code to send to PIs

**Comment by sylvainschmitt** [comment]
@mithilaunkule , I quickly made a script to get raw taxonomy to start working. Please have a look to it. You can update it to your case and then share the result by direct link with versioning as discussed for raw inventories.

**Comment by mithilaunkule** [comment]
> @mithilaunkule , I quickly made a script to get raw taxonomy to start working. Please have a look to it. You can update it to your case and then share the result by direct link with versioning as discussed for raw inventories.

Hi @sylvainschmitt are you talking about the "extract_raw_data.R"? Or the qmd files? I saw that you have already done a lot of work in both raw and cleaned qmd files. Thank you so much for so much work, it looks so good! I had also begun to work on a local version of it as it was a task assigned to me. Could you please tell me in advance so we both don't work on the same thing? I know that I am a bit slow, but I am just learning to use the git features, and I want to learn and improve. Hope I can try to reach your level of efficiency and speed :)

**Comment by sylvainschmitt** [comment]
`extract_raw_data.R`, yes this one.

**Comment by sylvainschmitt** [comment]
> Thank you so much for so much work, it looks so good! I had also begun to work on a local version of it as it was a task assigned to me.

Not sure to understand. But yes you were assigned on sharing and I was assigned on cleaning and phylogeny. So I made a quick version for me to start working. But you can update it and I will update my codes accordingly. We should just take care to have raw data versioning for me to keep up my codes up to date.

**Comment by mithilaunkule** [comment]
> > Thank you so much for so much work, it looks so good! I had also begun to work on a local version of it as it was a task assigned to me.
> 
> Not sure to understand. But yes you were assigned on sharing and I was assigned on cleaning and phylogeny. So I made a quick version for me to start working. But you can update it and I will update my codes accordingly. We should just take care to have raw data versioning for me to keep up my codes up to date.

ah ok so some small misunderstanding, I thought I will be cleaning as well. 

What updates does the extract_raw_data.r file need?

**Comment by sylvainschmitt** [comment]
> ah ok so some small misunderstanding, I thought I will be cleaning as well.

You may but you were not assigned to the issue. We can however change that and discuss it.

> What updates does the extract_raw_data.r file need?

First check the content and if you agree, and we may clean some part. Second, currently it does not deal with spurious harmonized data with wrong taxo. So You should decide if you clean the raw inventory data or if you deal with it here.
